In [24]:
from numpy.ma.core import zeros
from matplotlib.projections import process_projection_requirements

# Importing Necessary Libraries
import matplotlib.pyplot as plt
import cv2
import numpy as np
import math


def kMeans(data,number,classCenters):
  while(True):
      if(isinstance(data[0][0], np.uint8)):
        sumOfEachClass = np.zeros_like(classCenters, dtype=int)
      else:
        sumOfEachClass = np.zeros((number, len(classCenters[0])))
        newClassCenters= np.zeros_like(classCenters, dtype=int)
      countOfEachClass= np.zeros(len(classCenters), dtype=int)

      for x in data:
        for y in x:
          if(isinstance(y, np.uint8)):
            closestClassIndex = getClass1(y,classCenters)
            sumOfEachClass[closestClassIndex]+=y
          else:
            closestClassIndex = getClass2(y,classCenters)
            for i in range(len(classCenters[0])):
              sumOfEachClass[closestClassIndex][i]+=y[i]
          
          countOfEachClass[closestClassIndex]+=1
          
      if(isinstance(y,  np.uint8)):
        newClassCenters = np.divide(sumOfEachClass,countOfEachClass)
      else:
        for i in range(len(countOfEachClass)):
          if(countOfEachClass[i]==0):
            for j in range(len(y)):
              newClassCenters[i][j]=0
          else:
            for j in range(len(y)):
              newClassCenters[i][j]=sumOfEachClass[i][j]/countOfEachClass[i]

      newClassCenters[np.isnan(newClassCenters)] = 0
      print(newClassCenters)
      if((newClassCenters == classCenters).all()):
        finalClassCenters=classCenters
        break
      else:
        classCenters=newClassCenters

  data2 = np.zeros((len(data),len(data[0])), np.uint8)
  for i in range(len(data)):
    for j in range(len(data[i])):
            y = data[i][j]
            if(isinstance(y, np.uint8)):
              closestClassIndex = getClass1(y,finalClassCenters)
            else:
              closestClassIndex = getClass2(y,finalClassCenters)

            data[i][j]=finalClassCenters[closestClassIndex]
            data2[i][j]=closestClassIndex
  return data,data2


def getClass1(pixel,classCenters):
      min=9999
      minClass=500
      for center in classCenters:
        x=abs(pixel-center)
        if(x<min):
          min=x
          minClass=center
    
      i=0
      for center in classCenters:
        if(center==minClass):
          return i
        i=i+1

def getClass2(pixelRGB,classCenters):
      min=9999
      minClass=500
      for center in classCenters:
        sum=0
        for i in range(len(pixelRGB)):
          sum= sum + abs(pixelRGB[i]-center[i])**2
        if(sum==0): 
          x=0;
        else:
          x= math.log2(sum)

        if(x<min):
          min=x
          minClass=center
    
      index=0;
      for center in classCenters:
        flag= True;
        for i in range(len(center)):
          if(center[i]!=minClass[i]):
            flag= False
        if(flag):
          return index
        index=index+1
        

def getConfusionMatrix(img):
  
      arrOut = np.zeros((4,4))
      # arrOut=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
      for i in range(0,256):
        for j in range(0,256):
          if(img[i][j]==0):
            arrOut[0][0]=arrOut[0][0]+1
          else:
            if(img[i][j]==1):
              arrOut[0][1]=arrOut[0][1]+1
            if(img[i][j]==2):
              arrOut[0][2]=arrOut[0][2]+1
            if(img[i][j]==3):
              arrOut[0][3]=arrOut[0][3]+1

        for j in range(256,512):
          if(img[i][j]==1):
            arrOut[2][1]=arrOut[2][1]+1
          else:
            if(img[i][j]==0):
              arrOut[2][0]=arrOut[2][0]+1
            if(img[i][j]==2):
              arrOut[2][2]=arrOut[2][2]+1
            if(img[i][j]==3):
              arrOut[2][3]=arrOut[2][3]+1

      for i in range(256,512):
        for j in range(0,256):
          if(img[i][j]==2):
            arrOut[1][2]=arrOut[1][2]+1
          else:
            if(img[i][j]==0):
              arrOut[1][0]=arrOut[1][0]+1
            if(img[i][j]==1):
              arrOut[1][1]=arrOut[1][1]+1
            if(img[i][j]==3):
              arrOut[1][3]=arrOut[1][3]+1

        for j in range(256,512):
          if(img[i][j]==3):
            arrOut[3][3]=arrOut[3][3]+1
          else:
            if(img[i][j]==0):
              arrOut[3][0]=arrOut[3][0]+1
            if(img[i][j]==1):
              arrOut[3][1]=arrOut[3][1]+1
            if(img[i][j]==2):
              arrOut[3][2]=arrOut[3][2]+1
      return arrOut









In [25]:
ImgOriginal = cv2.imread('/content/Lion.jpeg', 1)
LionKMeans=kMeans(ImgOriginal ,3,[[173,173,173],[0,0,0],[203,203,203]])
cv2.imwrite('/content/LionKMeans.jpeg', LionKMeans[0])

[[101 137 162]
 [ 26  47  77]
 [226 219 210]]
[[ 98 136 162]
 [ 29  50  81]
 [220 214 207]]
[[ 97 135 162]
 [ 29  51  82]
 [217 213 206]]
[[ 96 135 162]
 [ 29  51  82]
 [216 212 206]]
[[ 96 134 161]
 [ 29  51  81]
 [215 212 205]]
[[ 95 134 161]
 [ 29  50  81]
 [214 212 205]]
[[ 95 133 161]
 [ 29  50  80]
 [214 211 205]]
[[ 95 133 161]
 [ 29  50  80]
 [214 211 205]]


True

In [ ]:
ImgOriginal2 = cv2.imread('/content/Rocks.jpg', 0)
RocksKMeans=kMeans(ImgOriginal2 ,4,[ 29.64438691 , 86.61732773 ,143.61820304 , 205.31797863])
cv2.imwrite('/content/RocksKMeans.jpg', RocksKMeans[0])